apiVersion: batch/v1
kind: Job
metadata:
  name: loader
spec:
  template:
    spec:
      containers:
      - name: loader
        image: python
        command: ["python",  "-c",  "import time;print('loading');time.sleep(10);print('loaded')"]
      restartPolicy: Never
  backoffLimit: 4