apiVersion: apps/v1
kind: Deployment
metadata:
  name: seeder-deployment
  labels:
    app: seeder
spec:
  replicas: 3
  selector:
    matchLabels:
      app: seeder
  template:
    metadata:
      labels:
        app: seeder
    spec:
      containers:
      - name: seeder
        image: arnoldedev/mary-dating-seeder
        env:
        - name: AMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-configmap
              key: rabbitmq_host
        - name: AMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-configmap
              key: rabbitmq_port
        - name: AMQ_OUTPUT_QUEUE
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-configmap
              key: seeder_output_queue
        - name: AMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secrets
              key: rabbitmq-default-user
        - name: AMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secrets
              key: rabbitmq-default-password